### ISSUE TITLE
Add option to pass flags to wofi

### ISSUE THREAD

**Issue by omnigenous** [schmidtandreas/wofi-pass#11]
I would love to be able to pass flags to wofi, specifically `--conf` flag, because I have `normal-window=true` in my wofi config which doesn't work well with wofi-pass. Also changing small things like prompt is also would be nice.

**Comment by schmidtandreas** [comment]
You can override the `_wofi` fuction in your config file. The config file will be sourced after the definition of the function `_wofi` inside the `wofi-pass` and will so override the main behavior with yours.

So just add this to your config file as example:

```bash
function _wofi() {
    wofi --normal-window "$@"
}
```

**Comment by omnigenous** [comment]
Okay, overwriting works! You misunderstood me a little, I wanted to run it in _default_ window rather than _normal_ window.

Here is how I done it:

`$HOME/.config/wofi-pass/config`:
```
function _wofi() {
    wofi --conf $HOME/.config/wofi-pass/wofi-config "$@"
}
```

`$HOME/.config/wofi-pass/wofi-config`:
```
prompt=Select passwords...
insensitive=true
```
^ notice no `normal-window`

Thank you <3
